server:
  port: 8000
spring:
  application:
    name: product
  config:
    import:
      - nacos:commons-mysql?group=commons
      - nacos:commons-redis?group=commons
#      - nacos:commons-redisson?group=commons
      - nacos:commons-redis-cache?group=commons
      - nacos:commons-callback?group=commons
      - nacos:commons?group=commons
  cloud:
    nacos:
      config:
        namespace: dev
        file-extension: yaml
      server-addr: 127.0.0.1:8848
  cache:
    redis:
      key-prefix: 'product::'
    cache-names:
      - category
      - product
      - skuItem
      - skuSaleAttrValue::values
  datasource:
    url: jdbc:mysql://localhost:3306/product?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: edu.nchu.mall.services.product.controller

