server:
  port: 8080
spring:
  threads:
    virtual:
      enabled: true
  application:
    name: gateway
  cloud:
    nacos:
      config:
        namespace: dev
        import-check:
          enabled: false
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: ruoyi
          uri:
            lb://ruoyi
          predicates:
            - Path=/ruoyi/**
          filters:
            - RewritePath=/ruoyi/?(?<segment>.*), /$\{segment}
        - id: product
          uri:
            lb://product
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/?(?<segment>.*), /$\{segment}
        - id: file
          uri:
            lb://file
          predicates:
            - Path=/file/**
          filters:
            - RewritePath=/file/?(?<segment>.*), /$\{segment}
        - id: member
          uri:
            lb://member
          predicates:
            - Path=/member/**
          filters:
            - RewritePath=/member/?(?<segment>.*), /$\{segment}
        - id: ware
          uri:
            lb://ware
          predicates:
            - Path=/ware/**
          filters:
            - RewritePath=/ware/?(?<segment>.*), /$\{segment}
        - id: search
          uri:
            lb://search
          predicates:
            - Path=/search/**
          filters:
            - RewritePath=/search/?(?<segment>.*), /$\{segment}
        - id: auth
          uri:
            lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}
        - id: cart
          uri:
            lb://cart
          predicates:
            - Path=/cart/**
          filters:
            - RewritePath=/cart/?(?<segment>.*), /$\{segment}
        - id: order
          uri:
            lb://order
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/?(?<segment>.*), /$\{segment}
fronted:
  url: localhost

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration-ms:
    refresh: 3600000
    access: 86400000
  cookie:
    name:
      refresh: smart-mall-refresh-token