server:
  port: 8080
spring:
  application:
    name: gateway
  config:
    import:
      - nacos:commons?group=commons
  cloud:
    nacos:
      config:
        namespace: dev
#        import-check:
#          enabled: false
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: ruoyi
          uri:
            lb://ruoyi
          predicates:
            - Path=/ruoyi/**
          filters:
            - RewritePath=/ruoyi/?(?<segment>.*), /$\{segment}
        - id: product
          uri:
            lb://product
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/?(?<segment>.*), /$\{segment}
        - id: file
          uri:
            lb://file
          predicates:
            - Path=/file/**
          filters:
            - RewritePath=/file/?(?<segment>.*), /$\{segment}
        - id: member
          uri:
            lb://member
          predicates:
            - Path=/member/**
          filters:
            - RewritePath=/member/?(?<segment>.*), /$\{segment}
        - id: ware
          uri:
            lb://ware
          predicates:
            - Path=/ware/**
          filters:
            - RewritePath=/ware/?(?<segment>.*), /$\{segment}
        - id: search
          uri:
            lb://search
          predicates:
            - Path=/search/**
          filters:
            - RewritePath=/search/?(?<segment>.*), /$\{segment}
fronted:
  url: localhost