server:
  port: 8080
spring:
  application:
    name: gateway
  config:
    import:
      - nacos:commons-mysql?group=commons
      - nacos:commons-redis?group=commons
      - nacos:commons-redis-cache?group=commons
  cloud:
    nacos:
      config:
        namespace: dev
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: ruoyi
          uri:
            http://localhost:8081
          predicates:
            - Path=/ruoyi/**
          filters:
            - RewritePath=/ruoyi/?(?<segment>.*), /$\{segment}
        - id: product
          uri:
            lb://product
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/?(?<segment>.*), /$\{segment}
fronted:
  url: localhost