server:
  port: 8300
spring:
  application:
    name: member
  config:
    import:
      - nacos:commons-mysql?group=commons
      - nacos:commons-redis?group=commons
      - nacos:commons-redis-cache?group=commons
      - nacos:commons?group=commons
  cloud:
    nacos:
      config:
        namespace: dev
        file-extension: yaml
      server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://localhost:3306/member?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: edu.nchu.mall.services.member.controller
